backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: pages
    label: Pages
    create: true
    slug: "{{slug}}"
    files:
      - file: src/pages/home/index.md
        label: Home Page
        name: home
        fields:
          #Needs to be updated
          - {label: Template Key, name: templateKey, widget: hidden, default: home-page}
          - {label: Main, name: main, widget: object, fields: [
              {label: Intro Heading, name: introHeading, widget: string},
              {label: Intro Body, name: introBody, widget: markdown},
              {label: Welcome Heading, name: welcomeHeading, widget: string},
              {label: Welcome Body, name: welcomeBody, widget: markdown},
              {label: DVD Title, name: dvdTitle, widget: string},
              {label: DVD Description, name: dvdDescription, widget: markdown}
            ]}
          - {label: Sidebar, name: sidebar, widget: list, fields: [
              {label: Heading, name: heading, widget: string},
              {label: Summary, name: summary, widget: string, required: false},
              {label: Links, name: links, widget: list, fields: [
                {label: Link Title, name: linkTitle, widget: string},
                {label: Link, name: link, widget: string}
              ]}
            ]}
          - {label: Support Us, name: supportUs, widget: object, fields: [
              {label: Heading, name: heading, widget: string},
              {label: Body, name: body, widget: markdown}
            ]}

      - file: src/pages/about/index.md
        label: About Page
        name: about
        fields:
          - {label: Template Key, name: templateKey, widget: hidden, default: about-page}
          - {label: Main, name: main, widget: object, fields: [
              {label: Title, name: title, widget: string},
              {label: Topics, name: topics, widget: list, fields: [
                {label: Heading, name: heading, widget: string},
                {label: Body, name: body, widget: markdown}
              ]}
            ]}

  # - name: custom pages
  #   label: Custom Pages
  #   folder: src/pages/custom
  #   create: true
  #   slug: {{slug}}
  #   fields:
  #     - {label: Template Key, name: templateKey, widget: hidden, default: custom-page}
  #     - {label: Title, name: title, widget: string, required: false}
  #     - {label: Image, name: image, widget: image, required: false}
  #     - {label: Heading, name: heading, widget: string, required: false}
  #     - {label: Subheading, name: subheading, widget: string, required: false}
  #     - {label: Description, name: description, widget: string, required: false}
  #     - {label: Body, name: body, widget: markdown, required: false}